apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
  labels: 
    app: reverseproxy
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app:  reverseproxy
  template: 
    metadata: 
      labels: 
        app: reverseproxy
    spec: 
      containers: 
      - name: reverseproxy
        image: trustekpo/udagram-reverseproxy:v5a
        imagePullPolicy: Always
        resources: 
          requests: 
            memory: "64Mi"
            cpu: "250m"
          limits: 
            memory: "1024Mi"
            cpu: "500m"
        envFrom:
          - secretRef: 
              name: env-secret
          - configMapRef:
              name: env-configmap
          - secretRef: 
              name: aws-secret
        ports:
          - containerPort: 8080
      restartPolicy: Always